services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 80s

  web:
    image: nitz/python
    build: .
    environment:
      PGPASSWORD: "${POSTGRES_PASSWORD}"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 443
      - 80

  bot:
    image: nitz/python
    build: .
    environment:
      PGPASSWORD: "${POSTGRES_PASSWORD}"
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
    depends_on:
      db:
        condition: service_healthy
    command: 'djang/manage.py bot'
